FROM putssander/spacy-json-nlp:base_v2

RUN python -m spacy download en_core_web_sm
RUN python -m spacy download en
RUN python -m spacy download de_core_news_sm
RUN python -m spacy download de
RUN python -m spacy download fr_core_news_sm
RUN python -m spacy download fr
RUN python -m spacy download es_core_news_sm
RUN python -m spacy download es
RUN python -m spacy download pt_core_news_sm
RUN python -m spacy download pt
RUN python -m spacy download it_core_news_sm
RUN python -m spacy download it
RUN python -m spacy download nl_core_news_sm
RUN python -m spacy download nl
RUN python -m spacy download el_core_news_sm
RUN python -m spacy download el
RUN python -m spacy download xx_ent_wiki_sm
RUN python -m spacy download xx

#RUN python -m spacy download en_core_web_lg
RUN python -m spacy download en_core_web_md